config/routes.rb
Rails.application.routes.draw do
  resources :breads
  get 'pages/home'
  get 'pages/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bread.rb
class Bread < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breads_controller.rb
class BreadsController < ApplicationController
  before_action :set_bread, only: %i[ show edit update destroy ]

  # GET /breads or /breads.json
  def index
    @breads = Bread.all
  end

  # GET /breads/1 or /breads/1.json
  def show
  end

  # GET /breads/new
  def new
    @bread = Bread.new
  end

  # GET /breads/1/edit
  def edit
  end

  # POST /breads or /breads.json
  def create
    @bread = Bread.new(bread_params)

    respond_to do |format|
      if @bread.save
        format.html { redirect_to bread_url(@bread), notice: "Bread was successfully created." }
        format.json { render :show, status: :created, location: @bread }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breads/1 or /breads/1.json
  def update
    respond_to do |format|
      if @bread.update(bread_params)
        format.html { redirect_to bread_url(@bread), notice: "Bread was successfully updated." }
        format.json { render :show, status: :ok, location: @bread }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breads/1 or /breads/1.json
  def destroy
    @bread.destroy

    respond_to do |format|
      format.html { redirect_to breads_url, notice: "Bread was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bread
      @bread = Bread.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bread_params
      params.require(:bread).permit(:name, :story)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breads_helper.rb
module BreadsHelper
end

app/views/breads/_bread.html.erb
<div id="<%= dom_id bread %>">
  <p>
    <strong>Name:</strong>
    <%= bread.name %>
  </p>

  <p>
    <strong>Story:</strong>
    <%= bread.story %>
  </p>

</div>

app/views/breads/_form.html.erb
<%= form_with(model: bread) do |form| %>
  <% if bread.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bread.errors.count, "error") %> prohibited this bread from being saved:</h2>

      <ul>
        <% bread.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :story, style: "display: block" %>
    <%= form.text_area :story %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breads/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/breads/edit.html.erb
<h1>Editing bread</h1>

<%= render "form", bread: @bread %>

<br>

<div>
  <%= link_to "Show this bread", @bread %> |
  <%= link_to "Back to breads", breads_path %>
</div>

app/views/breads/index.html.erb
<p style="color: green"><%= notice %></p>
<%= render "navbar"%>
<h1>Breads</h1>

<div id="breads">
  <% @breads.each do |bread| %>
    <%= render bread %>
    <p>
      <%= link_to "Show this bread", bread %>
    </p>
  <% end %>
</div>

<%= link_to "New bread", new_bread_path %>

app/views/breads/new.html.erb
<h1>New bread</h1>

<%= render "form", bread: @bread %>

<br>

<div>
  <%= link_to "Back to breads", breads_path %>
</div>

app/views/breads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bread %>

<div>
  <%= link_to "Edit this bread", edit_bread_path(@bread) %> |
  <%= link_to "Back to breads", breads_path %>

  <%= button_to "Destroy this bread", @bread, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breaddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>